export const homeTiles = [
  {
    title: 'Member Login',
    description: 'Manage your account',
    icon: 'badge',
    url: 'https://www.ourclublogin.com/Account/Login/500212',
    backgroundColor: '#9EE09E',
    tile_order: 1,
    tile_id: 1,
  },
  {
    title: 'Schedule',
    description: 'Calendar updates',
    icon: 'event-available',
    url: 'https://nwpersonaltraining.com/',
    backgroundColor: '#CC99C9',
    tile_order: 2,
    tile_id: 2,
  },
  {
    title: 'Fitness Assessment',
    description: 'Track your fitness',
    icon: 'accessibility',
    url: 'https://nwpersonaltraining.com/',
    backgroundColor: '#BE9EFF',
    tile_order: 3,
    tile_id: 3,
  },
  {
    title: 'Facebook',
    description: 'Follow us on Facebook',
    icon: 'facebook',
    url: 'https://www.facebook.com/delnorhfc/',
    backgroundColor: '#4267B2',
    tile_order: 4,
    tile_id: 4,
  },
  {
    title: 'Card',
    description: 'Your membership',
    icon: 'qr-code-scanner',
    url: 'https://nwpersonaltraining.com/',
    backgroundColor: '#FEB144',
    tile_order: 5,
    tile_id: 5,
  },
  {
    title: 'Occupancy',
    description: 'Center Occupancy',
    icon: 'people',
    url: 'https://www.delnorhfc.com/about/center-occupancy/?doing_wp_cron=1631701328.8954908847808837890625',
    backgroundColor: '#88C0FC',
    tile_order: 6,
    tile_id: 6,
  },
  {
    title: 'Contact',
    description: 'Contact and Hours',
    icon: 'contact-page',
    url: 'https://nwpersonaltraining.com/',
    backgroundColor: '#FF6663',
    tile_order: 7,
    tile_id: 7,
  },
];

export const scheduledEvents = [
  {
    id: 13,
    date: '2021-09-28T10:55:46+05:30',
    activity_start_time: '5:30:00',
    activity_end_time: '6:15:00',
    activity: 'Kickboxing',
    description: 'this is the description',
    category: 'Cardio/Strength',
    resource: 'Aerobic Studio',
    instructor: 'Other',
  },
  {
    id: 14,
    date: '2021-09-28T10:55:46+05:30',
    activity_start_time: '7:30:00',
    activity_end_time: '8:30:00',
    activity: 'Deep Water',
    description: 'this is the description',
    category: 'Aquatic Class',
    resource: 'Pool',
    instructor: 'Other',
  },
  {
    id: 15,
    date: '2021-09-28T10:55:46+05:30',
    activity_start_time: '8:30:00',
    activity_end_time: '9:30:00',
    activity: 'Shallow Water',
    description: 'this is the description',
    category: 'Aquatic Class, Cardio / Strength',
    resource: 'Pool',
    instructor: 'Other',
  },
  {
    id: 16,
    date: '2021-09-28T10:55:46+05:30',
    activity_start_time: '8:15:00',
    activity_end_time: '9:00:00',
    activity: 'Cycling',
    description: 'this is the description',
    category: 'Cycling Class',
    resource: 'Cycle Studio',
    instructor: 'Other',
  },
  {
    id: 17,
    date: '2021-09-28T10:55:46+05:30',
    activity_start_time: '9:15:00',
    activity_end_time: '10:00:00',
    activity: 'Outdoor Functional Training',
    description: 'this is the description',
    category: 'Special activity',
    resource: 'South Lawn',
    instructor: 'Other',
  },
  {
    id: 18,
    date: '2021-09-28T10:55:46+05:30',
    activity_start_time: '8:30:00',
    activity_end_time: '9:45:00',
    activity: 'Gentle Yoga',
    description: 'this is the description',
    category: 'Gentle Yoga',
    resource: 'Gentle Yoga',
    instructor: 'Other',
  },
  {
    id: 19,
    date: '2021-09-29T10:55:46+05:30',
    activity_start_time: '5:30:00',
    activity_end_time: '6:15:00',
    activity: 'Kickboxing',
    description: 'this is the description',
    category: 'Cardio/Strength',
    resource: 'Aerobic Studio',
    instructor: 'Other',
  },
  {
    id: 20,
    date: '2021-09-29T10:55:46+05:30',
    activity_start_time: '7:30:00',
    activity_end_time: '8:30:00',
    activity: 'Deep Water',
    description: 'this is the description',
    category: 'Aquatic Class',
    resource: 'Pool',
    instructor: 'Other',
  },
  {
    id: 21,
    date: '2021-09-29T10:55:46+05:30',
    activity_start_time: '8:30:00',
    activity_end_time: '9:30:00',
    activity: 'Shallow Water',
    description: 'this is the description',
    category: 'Aquatic Class, Cardio / Strength',
    resource: 'Pool',
    instructor: 'Other',
  },
  {
    id: 22,
    date: '2021-09-29T10:55:46+05:30',
    activity_start_time: '8:15:00',
    activity_end_time: '9:00:00',
    activity: 'Cycling',
    description: 'this is the description',
    category: 'Cycling Class',
    resource: 'Cycle Studio',
    instructor: 'Other',
  },
  {
    id: 23,
    date: '2021-09-29T10:55:46+05:30',
    activity_start_time: '9:15:00',
    activity_end_time: '10:00:00',
    activity: 'Outdoor Functional Training',
    description: 'this is the description',
    category: 'Special activity',
    resource: 'South Lawn',
    instructor: 'Other',
  },
  {
    id: 24,
    date: '2021-09-29T10:55:46+05:30',
    activity_start_time: '8:30:00',
    activity_end_time: '9:45:00',
    activity: 'Gentle Yoga',
    description: 'this is the description',
    category: 'Gentle Yoga',
    resource: 'Gentle Yoga',
    instructor: 'Other',
  },
  {
    id: 25,
    date: '2021-09-30T10:55:46+05:30',
    activity_start_time: '5:30:00',
    activity_end_time: '6:15:00',
    activity: 'Kickboxing',
    description: 'this is the description',
    category: 'Cardio/Strength',
    resource: 'Aerobic Studio',
    instructor: 'Other',
  },
  {
    id: 26,
    date: '2021-09-30T10:55:46+05:30',
    activity_start_time: '7:30:00',
    activity_end_time: '8:30:00',
    activity: 'Deep Water',
    description: 'this is the description',
    category: 'Aquatic Class',
    resource: 'Pool',
    instructor: 'Other',
  },
  {
    id: 27,
    date: '2021-09-30T10:55:46+05:30',
    activity_start_time: '8:30:00',
    activity_end_time: '9:30:00',
    activity: 'Shallow Water',
    description: 'this is the description',
    category: 'Aquatic Class, Cardio / Strength',
    resource: 'Pool',
    instructor: 'Other',
  },
  {
    id: 28,
    date: '2021-09-30T10:55:46+05:30',
    activity_start_time: '8:15:00',
    activity_end_time: '9:00:00',
    activity: 'Cycling',
    description: 'this is the description',
    category: 'Cycling Class',
    resource: 'Cycle Studio',
    instructor: 'Other',
  },
  {
    id: 29,
    date: '2021-09-30T10:55:46+05:30',
    activity_start_time: '9:15:00',
    activity_end_time: '10:00:00',
    activity: 'Outdoor Functional Training',
    description: 'this is the description',
    category: 'Special activity',
    resource: 'South Lawn',
    instructor: 'Other',
  },
  {
    id: 30,
    date: '2021-09-30T10:55:46+05:30',
    activity_start_time: '8:30:00',
    activity_end_time: '9:45:00',
    activity: 'Gentle Yoga',
    description: 'this is the description',
    category: 'Gentle Yoga',
    resource: 'Gentle Yoga',
    instructor: 'Other',
  },
  {
    id: 31,
    date: '2021-10-01T10:55:46+05:30',
    activity_start_time: '5:30:00',
    activity_end_time: '6:15:00',
    activity: 'Kickboxing',
    description: 'this is the description',
    category: 'Cardio/Strength',
    resource: 'Aerobic Studio',
    instructor: 'Other',
  },
  {
    id: 32,
    date: '2021-10-01T10:55:46+05:30',
    activity_start_time: '7:30:00',
    activity_end_time: '8:30:00',
    activity: 'Deep Water',
    description: 'this is the description',
    category: 'Aquatic Class',
    resource: 'Pool',
    instructor: 'Other',
  },
  {
    id: 33,
    date: '2021-10-01T10:55:46+05:30',
    activity_start_time: '8:30:00',
    activity_end_time: '9:30:00',
    activity: 'Shallow Water',
    description: 'this is the description',
    category: 'Aquatic Class, Cardio / Strength',
    resource: 'Pool',
    instructor: 'Other',
  },
  {
    id: 34,
    date: '2021-10-01T10:55:46+05:30',
    activity_start_time: '8:15:00',
    activity_end_time: '9:00:00',
    activity: 'Cycling',
    description: 'this is the description',
    category: 'Cycling Class',
    resource: 'Cycle Studio',
    instructor: 'Other',
  },
  {
    id: 35,
    date: '2021-10-01T10:55:46+05:30',
    activity_start_time: '9:15:00',
    activity_end_time: '10:00:00',
    activity: 'Outdoor Functional Training',
    description: 'this is the description',
    category: 'Special activity',
    resource: 'South Lawn',
    instructor: 'Other',
  },
  {
    id: 36,
    date: '2021-10-01T10:55:46+05:30',
    activity_start_time: '8:30:00',
    activity_end_time: '9:45:00',
    activity: 'Gentle Yoga',
    description: 'this is the description',
    category: 'Gentle Yoga',
    resource: 'Gentle Yoga',
    instructor: 'Other',
  },
  {
    id: 37,
    date: '2021-10-02T10:55:46+05:30',
    activity_start_time: '5:30:00',
    activity_end_time: '6:15:00',
    activity: 'Kickboxing',
    description: 'this is the description',
    category: 'Cardio/Strength',
    resource: 'Aerobic Studio',
    instructor: 'Other',
  },
  {
    id: 38,
    date: '2021-10-02T10:55:46+05:30',
    activity_start_time: '7:30:00',
    activity_end_time: '8:30:00',
    activity: 'Deep Water',
    description: 'this is the description',
    category: 'Aquatic Class',
    resource: 'Pool',
    instructor: 'Other',
  },
  {
    id: 39,
    date: '2021-10-02T10:55:46+05:30',
    activity_start_time: '8:30:00',
    activity_end_time: '9:30:00',
    activity: 'Shallow Water',
    description: 'this is the description',
    category: 'Aquatic Class, Cardio / Strength',
    resource: 'Pool',
    instructor: 'Other',
  },
  {
    id: 40,
    date: '2021-10-02T10:55:46+05:30',
    activity_start_time: '8:15:00',
    activity_end_time: '9:00:00',
    activity: 'Cycling',
    description: 'this is the description',
    category: 'Cycling Class',
    resource: 'Cycle Studio',
    instructor: 'Other',
  },
  {
    id: 41,
    date: '2021-10-02T10:55:46+05:30',
    activity_start_time: '9:15:00',
    activity_end_time: '10:00:00',
    activity: 'Outdoor Functional Training',
    description: 'this is the description',
    category: 'Special activity',
    resource: 'South Lawn',
    instructor: 'Other',
  },
  {
    id: 42,
    date: '2021-10-02T10:55:46+05:30',
    activity_start_time: '8:30:00',
    activity_end_time: '9:45:00',
    activity: 'Gentle Yoga',
    description: 'this is the description',
    category: 'Gentle Yoga',
    resource: 'Gentle Yoga',
    instructor: 'Other',
  },
  {
    id: 43,
    date: '2021-10-03T10:55:46+05:30',
    activity_start_time: '5:30:00',
    activity_end_time: '6:15:00',
    activity: 'Kickboxing',
    description: 'this is the description',
    category: 'Cardio/Strength',
    resource: 'Aerobic Studio',
    instructor: 'Other',
  },
  {
    id: 44,
    date: '2021-10-03T10:55:46+05:30',
    activity_start_time: '7:30:00',
    activity_end_time: '8:30:00',
    activity: 'Deep Water',
    description: 'this is the description',
    category: 'Aquatic Class',
    resource: 'Pool',
    instructor: 'Other',
  },
  {
    id: 45,
    date: '2021-10-03T10:55:46+05:30',
    activity_start_time: '8:30:00',
    activity_end_time: '9:30:00',
    activity: 'Shallow Water',
    description: 'this is the description',
    category: 'Aquatic Class, Cardio / Strength',
    resource: 'Pool',
    instructor: 'Other',
  },
  {
    id: 46,
    date: '2021-10-03T10:55:46+05:30',
    activity_start_time: '8:15:00',
    activity_end_time: '9:00:00',
    activity: 'Cycling',
    description: 'this is the description',
    category: 'Cycling Class',
    resource: 'Cycle Studio',
    instructor: 'Other',
  },
  {
    id: 47,
    date: '2021-10-03T10:55:46+05:30',
    activity_start_time: '9:15:00',
    activity_end_time: '10:00:00',
    activity: 'Outdoor Functional Training',
    description: 'this is the description',
    category: 'Special activity',
    resource: 'South Lawn',
    instructor: 'Other',
  },
  {
    id: 48,
    date: '2021-10-03T10:55:46+05:30',
    activity_start_time: '8:30:00',
    activity_end_time: '9:45:00',
    activity: 'Gentle Yoga',
    description: 'this is the description',
    category: 'Gentle Yoga',
    resource: 'Gentle Yoga',
    instructor: 'Other',
  },
  {
    id: 49,
    date: '2021-10-04T10:55:46+05:30',
    activity_start_time: '5:30:00',
    activity_end_time: '6:15:00',
    activity: 'Kickboxing',
    description: 'this is the description',
    category: 'Cardio/Strength',
    resource: 'Aerobic Studio',
    instructor: 'Other',
  },
  {
    id: 50,
    date: '2021-10-04T10:55:46+05:30',
    activity_start_time: '7:30:00',
    activity_end_time: '8:30:00',
    activity: 'Deep Water',
    description: 'this is the description',
    category: 'Aquatic Class',
    resource: 'Pool',
    instructor: 'Other',
  },
  {
    id: 51,
    date: '2021-10-04T10:55:46+05:30',
    activity_start_time: '8:30:00',
    activity_end_time: '9:30:00',
    activity: 'Shallow Water',
    description: 'this is the description',
    category: 'Aquatic Class, Cardio / Strength',
    resource: 'Pool',
    instructor: 'Other',
  },
  {
    id: 52,
    date: '2021-10-04T10:55:46+05:30',
    activity_start_time: '8:15:00',
    activity_end_time: '9:00:00',
    activity: 'Cycling',
    description: 'this is the description',
    category: 'Cycling Class',
    resource: 'Cycle Studio',
    instructor: 'Other',
  },
  {
    id: 53,
    date: '2021-10-04T10:55:46+05:30',
    activity_start_time: '9:15:00',
    activity_end_time: '10:00:00',
    activity: 'Outdoor Functional Training',
    description: 'this is the description',
    category: 'Special activity',
    resource: 'South Lawn',
    instructor: 'Other',
  },
  {
    id: 54,
    date: '2021-10-04T10:55:46+05:30',
    activity_start_time: '8:30:00',
    activity_end_time: '9:45:00',
    activity: 'Gentle Yoga',
    description: 'this is the description',
    category: 'Gentle Yoga',
    resource: 'Gentle Yoga',
    instructor: 'Other',
  },
];

export const contactAndHours = {
  centerName: 'Nothwestern Medicine',
  branchName: 'Delnor Health & Fitness Center',
  socialMediaLinks: {
    facebookLink: 'https://www.facebook.com/delnorhfc/',
    twitterLink: 'https://twitter.com',
  },
  hours: [
    {
      day: 'Monday',
      start: '5:00 am',
      end: '9:00 pm',
    },
    {
      day: 'Tuesday',
      start: '5:00 am',
      end: '9:00 pm',
    },
    {
      day: 'Wednesday',
      start: '5:00 am',
      end: '9:00 pm',
    },
    {
      day: 'Thursday',
      start: '5:00 am',
      end: '9:00 pm',
    },
    {
      day: 'Friday',
      start: '5:00 am',
      end: '7:00 pm',
    },
    {
      day: 'Saturday',
      start: '7:00 am',
      end: '3:00 pm',
    },
    {
      day: 'Sunday',
      start: '10:00 am',
      end: '2:00 pm',
    },
  ],
  address: {
    fullAddress: '296 S Randall Road, Geneva, IL 60134',
    googleMapsLink: 'https://goo.gl/maps/EG1iAJrdSWif69fm8',
  },
  phoneNumber: '630.938.9000',
  email: 'info@delnorhfc.com',
  website: 'https://www.delnorhfc.com/',
};

export const notifications = [
  {
    title: 'Lorem ipsum dolor sit amet consectetur',
    notificationMessage:
      'Lorem One ipsum dolor sit amet consectetur adipisicing elit. Dolor ipsa minima rem nemo debitis incidunt dignissimos, molestias quis enim numquam.',
    image: 'https://via.placeholder.com/65x65',
    link: null,
  },
  {
    title: null,
    notificationMessage:
      'Lorem Two ipsum dolor sit amet consectetur adipisicing elit. Dolor ipsa minima rem nemo debitis incidunt dignissimos, molestias quis enim numquam.',
    image: 'https://via.placeholder.com/65x65',
    link: 'https://google.com',
  },
  {
    title: 'Lorem ipsum dolor sit amet consectetur',
    notificationMessage:
      'Lorem Three ipsum dolor sit amet consectetur adipisicing elit. Dolor ipsa minima rem nemo debitis incidunt dignissimos, molestias quis enim numquam.',
    image: 'https://via.placeholder.com/65x65',
    link: null,
  },
  {
    title: null,
    notificationMessage:
      'Lorem Four ipsum dolor sit amet consectetur adipisicing elit. Dolor ipsa minima rem nemo debitis incidunt dignissimos, molestias quis enim numquam.',
    image: 'https://via.placeholder.com/65x65',
    link: 'https://google.com',
  },
  {
    title: 'Lorem ipsum dolor sit amet consectetur',
    notificationMessage:
      'Lorem Five ipsum dolor sit amet consectetur adipisicing elit. Dolor ipsa minima rem nemo debitis incidunt dignissimos, molestias quis enim numquam.',
    image: 'https://via.placeholder.com/65x65',
    link: null,
  },
  {
    title: null,
    notificationMessage:
      'Lorem Six ipsum dolor sit amet consectetur adipisicing elit. Dolor ipsa minima rem nemo debitis incidunt dignissimos, molestias quis enim numquam.',
    image: 'https://via.placeholder.com/65x65',
    link: 'https://google.com',
  },
];

export const config = {
  primaryColor: '#796AC6',
  secondaryColor: '#FEB144',
  primaryTextColor: '#000000',
  secondaryTextColor: '#FFFFFF',
};

export const fitnessDataQR = [
  {
    typ: 'age',
    val: 23,
  },
  {
    typ: 'gender',
    val: 0,
  },
  {
    typ: 'height',
    val: 71,
    val_u: 'inch',
  },
  {
    typ: 'weight',
    val: 211.6,
    val_u: 'lbs',
  },
  {
    typ: 'bmi',
    val: 30.6,
  },
  {
    typ: 'bmi_rating',
    val: 2,
  },
  {
    typ: 'fat',
    val: 24,
  },
  {
    typ: 'fat_essential',
    val: 10,
    val_u: 'lbs',
  },
  {
    typ: 'fat_reserve',
    val: 31,
    val_u: 'lbs',
  },
  {
    typ: 'fat_excess',
    val: 11.4,
    val_u: 'lbs',
  },
  {
    typ: 'fat_free_mass',
    val: 166,
    val_u: 'lbs',
  },
  {
    typ: 'fat_rating',
    val: 2,
  },
  {
    typ: 'body_water',
    val: 51.4,
  },
  {
    typ: 'bmr',
    val: 1941,
  },
];

export const fitnessData = [
  {
    date: '2021-10-25T15:12:50.000Z',
    device_id: 'C4C2DBF6-4BCA-423A-B04F-58B3D16A232F',
    usr_id: 'USR_00025',
    data: [
      {
        typ: 'age',
        val: 57,
      },
      {
        typ: 'gender',
        val: 0,
      },
      {
        typ: 'height',
        val: 75,
        val_u: 'inch',
      },
      {
        typ: 'weight',
        val: 190.4,
        val_u: 'lbs',
      },
      {
        typ: 'bmi',
        val: 24.3,
      },
      {
        typ: 'bmi_rating',
        val: 2,
      },
      {
        typ: 'fat',
        val: 20,
      },
      {
        typ: 'fat_essential',
        val: 10,
        val_u: 'lbs',
      },
      {
        typ: 'fat_reserve',
        val: 31,
        val_u: 'lbs',
      },
      {
        typ: 'fat_excess',
        val: 11.4,
        val_u: 'lbs',
      },
      {
        typ: 'fat_free_mass',
        val: 150,
        val_u: 'lbs',
      },
      {
        typ: 'fat_rating',
        val: 2,
      },
      {
        typ: 'body_water',
        val: 50,
      },
      {
        typ: 'bmr',
        val: 1998,
      },
    ],
  },
];

// export const fitnessData = [
//   {
//     date: '2021-10-08T00:00:00.000Z',
//     data: [
//       {
//         typ: 'age',
//         val: 57,
//       },
//       {
//         typ: 'gender',
//         val: 0,
//       },
//       {
//         typ: 'height',
//         val: 75,
//         val_u: 'inch',
//       },
//       {
//         typ: 'weight',
//         val: 190.4,
//         val_u: 'lbs',
//       },
//       {
//         typ: 'bmi',
//         val: 24.3,
//       },
//       {
//         typ: 'bmi_rating',
//         val: 2,
//       },
//       {
//         typ: 'fat',
//         val: 20,
//       },
//       {
//         typ: 'fat_essential',
//         val: 10,
//         val_u: 'lbs',
//       },
//       {
//         typ: 'fat_reserve',
//         val: 31,
//         val_u: 'lbs',
//       },
//       {
//         typ: 'fat_excess',
//         val: 11.4,
//         val_u: 'lbs',
//       },
//       {
//         typ: 'fat_free_mass',
//         val: 150,
//         val_u: 'lbs',
//       },
//       {
//         typ: 'fat_rating',
//         val: 2,
//       },
//       {
//         typ: 'body_water',
//         val: 50,
//       },
//       {
//         typ: 'bmr',
//         val: 1998,
//       },
//     ],
//   },
//   {
//     date: '2021-10-07T00:00:00.000Z',
//     data: [
//       {
//         typ: 'age',
//         val: 57,
//       },
//       {
//         typ: 'gender',
//         val: 0,
//       },
//       {
//         typ: 'height',
//         val: 75,
//         val_u: 'inch',
//       },
//       {
//         typ: 'weight',
//         val: 230,
//         val_u: 'lbs',
//       },
//       {
//         typ: 'bmi',
//         val: 29.3,
//       },
//       {
//         typ: 'bmi_rating',
//         val: 2,
//       },
//       {
//         typ: 'fat',
//         val: 29,
//       },
//       {
//         typ: 'fat_essential',
//         val: 10,
//         val_u: 'lbs',
//       },
//       {
//         typ: 'fat_reserve',
//         val: 31,
//         val_u: 'lbs',
//       },
//       {
//         typ: 'fat_excess',
//         val: 11.4,
//         val_u: 'lbs',
//       },
//       {
//         typ: 'fat_free_mass',
//         val: 199,
//         val_u: 'lbs',
//       },
//       {
//         typ: 'fat_rating',
//         val: 2,
//       },
//       {
//         typ: 'body_water',
//         val: 52.4,
//       },
//       {
//         typ: 'bmr',
//         val: 1891,
//       },
//     ],
//   },
//   {
//     date: '2021-10-06T00:00:00.000Z',
//     data: [
//       {
//         typ: 'age',
//         val: 57,
//       },
//       {
//         typ: 'gender',
//         val: 0,
//       },
//       {
//         typ: 'height',
//         val: 75,
//         val_u: 'inch',
//       },
//       {
//         typ: 'weight',
//         val: 170,
//         val_u: 'lbs',
//       },
//       {
//         typ: 'bmi',
//         val: 24,
//       },
//       {
//         typ: 'bmi_rating',
//         val: 2,
//       },
//       {
//         typ: 'fat',
//         val: 22,
//       },
//       {
//         typ: 'fat_essential',
//         val: 10,
//         val_u: 'lbs',
//       },
//       {
//         typ: 'fat_reserve',
//         val: 31,
//         val_u: 'lbs',
//       },
//       {
//         typ: 'fat_excess',
//         val: 11.4,
//         val_u: 'lbs',
//       },
//       {
//         typ: 'fat_free_mass',
//         val: 152,
//         val_u: 'lbs',
//       },
//       {
//         typ: 'fat_rating',
//         val: 2,
//       },
//       {
//         typ: 'body_water',
//         val: 55,
//       },
//       {
//         typ: 'bmr',
//         val: 1999,
//       },
//     ],
//   },
//   {
//     date: '2021-10-05T00:00:00.000Z',
//     data: [
//       {
//         typ: 'age',
//         val: 57,
//       },
//       {
//         typ: 'gender',
//         val: 0,
//       },
//       {
//         typ: 'height',
//         val: 75,
//         val_u: 'inch',
//       },
//       {
//         typ: 'weight',
//         val: 248.4,
//         val_u: 'lbs',
//       },
//       {
//         typ: 'bmi',
//         val: 25.3,
//       },
//       {
//         typ: 'bmi_rating',
//         val: 2,
//       },
//       {
//         typ: 'fat',
//         val: 27,
//       },
//       {
//         typ: 'fat_essential',
//         val: 10,
//         val_u: 'lbs',
//       },
//       {
//         typ: 'fat_reserve',
//         val: 31,
//         val_u: 'lbs',
//       },
//       {
//         typ: 'fat_excess',
//         val: 11.4,
//         val_u: 'lbs',
//       },
//       {
//         typ: 'fat_free_mass',
//         val: 169,
//         val_u: 'lbs',
//       },
//       {
//         typ: 'fat_rating',
//         val: 2,
//       },
//       {
//         typ: 'body_water',
//         val: 69.4,
//       },
//       {
//         typ: 'bmr',
//         val: 1969,
//       },
//     ],
//   },
//   {
//     date: '2021-10-04T00:00:00.000Z',
//     data: [
//       {
//         typ: 'age',
//         val: 57,
//       },
//       {
//         typ: 'gender',
//         val: 0,
//       },
//       {
//         typ: 'height',
//         val: 75,
//         val_u: 'inch',
//       },
//       {
//         typ: 'weight',
//         val: 218.4,
//         val_u: 'lbs',
//       },
//       {
//         typ: 'bmi',
//         val: 27.3,
//       },
//       {
//         typ: 'bmi_rating',
//         val: 2,
//       },
//       {
//         typ: 'fat',
//         val: 24,
//       },
//       {
//         typ: 'fat_essential',
//         val: 10,
//         val_u: 'lbs',
//       },
//       {
//         typ: 'fat_reserve',
//         val: 31,
//         val_u: 'lbs',
//       },
//       {
//         typ: 'fat_excess',
//         val: 11.4,
//         val_u: 'lbs',
//       },
//       {
//         typ: 'fat_free_mass',
//         val: 166,
//         val_u: 'lbs',
//       },
//       {
//         typ: 'fat_rating',
//         val: 2,
//       },
//       {
//         typ: 'body_water',
//         val: 51.4,
//       },
//       {
//         typ: 'bmr',
//         val: 1941,
//       },
//     ],
//   },
// ];

export const emptyFitnessData = [];
