export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';
export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const FETCH_USER_DATA_ERROR = 'FETCH_USER_DATA_ERROR';
export const FETCH_SEARCH_RESULT = 'FETCH_SEARCH_RESULT';
export const FETCH_SEARCH_RESULT_ERROR = 'FETCH_SEARCH_RESULT_ERROR';
export const CLEAR_SEARCH_RESULT = 'CLEAR_SEARCH_RESULT';
